CREATE DATABASE QLTV
USE [QLTV]
GO

CREATE TABLE [dbo].[NXB](
	[MANXB] [varchar](10) NOT NULL,
	[TENNXB] [nvarchar](50) NULL,
	[DIACHI] [nvarchar](100) NOT NULL,
	[SDT] [varchar](10) NOT NULL,
	[WEBSIZE] [varchar](100) NOT NULL,
	[EMAIL] [varchar](100) NOT NULL,
 CONSTRAINT [PK_NXB] PRIMARY KEY 
(
	[MANXB] ASC
)
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[NHANVIEN](
	[MANV] [varchar](10) NOT NULL,
	[TENNV] [nvarchar](50) NULL,
	[NAMSINH] [date] NULL,
	[DIACHI] [nvarchar](100) NULL,
	[SDT] [varchar](10) NULL,
	[EMAIL] [varchar](50) NULL,
	[NGAYVAOLAM] [date] NOT NULL,
	[GIOITINH] [nvarchar](10) NOT NULL,
 CONSTRAINT [PK_NHANVIEN] PRIMARY KEY 
(
	[MANV] ASC
)
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[LOAISACH](
	[MALOAI] [varchar](10) NOT NULL,
	[TENLOAI] [nvarchar](50) NULL,
	[MAVT] [varchar](10) NULL,
 CONSTRAINT [PK_LOAISACH] PRIMARY KEY 
(
	[MALOAI] ASC
)
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[DOCGIA](
	[MADG] [varchar](10) NOT NULL,
	[HOTEN] [nvarchar](50) NULL,
	[NAMSINH] [date] NULL,
	[DIACHI] [nvarchar](100) NULL,
	[SDT] [varchar](10) NULL,
	[EMAIL] [varchar](50) NULL,
	[GIOITINH] [nvarchar](10) NOT NULL,
 CONSTRAINT [PK_DOCGIA] PRIMARY KEY 
(
	[MADG] ASC
)
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[CHUCVU](
	[MACV] [varchar](10) NOT NULL,
	[TENCV] [nvarchar](50) NULL,
 CONSTRAINT [PK_CHUCVU] PRIMARY KEY 
(
	[MACV] ASC
)
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[VITRI](
	[MAVT] [varchar](10) NOT NULL,
	[TENVITRI] [nvarchar](50) NULL,
 CONSTRAINT [PK_VITRI] PRIMARY KEY 
(
	[MAVT] ASC
)
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[TAIKHOAN](
	[MATK] [varchar](10) NOT NULL,
	[TENTK] [varchar](20) NULL,
	[MATKHAU] [varchar](32) NULL,
	[MANV] [varchar](10) NOT NULL,
	[MACV] [varchar](10) NOT NULL,
 CONSTRAINT [PK_TAIKHOAN] PRIMARY KEY 
(
	[MATK] ASC,
	[MANV] ASC,
	[MACV] ASC
)
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[PHIEUMUON](
	[MAPM] [varchar](10) NOT NULL,
	[MANV] [varchar](10) NULL,
	[MADG] [varchar](10) NULL,
	[NGAYMUON] [date] NOT NULL,
	[SOLUONG] [int] NULL,
	[TRANGTHAI] [nvarchar](20) NOT NULL,
 CONSTRAINT [PK_PHIEUMUON] PRIMARY KEY 
(
	[MAPM] ASC
)
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[SACH](
	[MASACH] [varchar](10) NOT NULL,
	[TENSACH] [nvarchar](100) NULL,
	[TACGIA] [nvarchar](100) NULL,
	[SOLUONG] [int] NOT NULL,
	[NAMXB] [numeric](4, 0) NULL,
	[MANXB] [varchar](10) NOT NULL,
	[MALOAI] [varchar](10) NULL,
	[GIATIEN] [int] NULL,
 CONSTRAINT [PK_SACH] PRIMARY KEY 
(
	[MASACH] ASC
)
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[PHIEUPHAT](
	[MAPHAT] [varchar](10) NOT NULL,
	[MAPM] [varchar](10) NOT NULL,
	[NGAYPHAT] [date] NOT NULL,
	[TONGTIENPHAT] [int] NOT NULL,
 CONSTRAINT [PK_PHIEUPHAT] PRIMARY KEY 
(
	[MAPHAT] ASC
)
) ON [PRIMARY]
GO


CREATE TABLE [dbo].[CTPP](
	[MAPHAT] [varchar](10) NOT NULL,
	[MASACH] [varchar](10) NOT NULL,
	[LYDOPHAT] [nvarchar](50) NOT NULL,
	[SOLUONG] [int] NOT NULL,
	[DONVITINH] [nvarchar](10) NULL,
	[TIEN] [int] NOT NULL
) ON [PRIMARY]

/****** Object:  Table [dbo].[CTPM]    Script Date: 12/03/2021 14:38:17 ******/

CREATE TABLE [dbo].[CTPM](
	[MAPM] [varchar](10) NOT NULL,
	[MASACH] [varchar](10) NOT NULL,
	[HENTRA] [date] NULL,
	[SOLUONG] [int] NULL,
	[TRANGTHAI] [nvarchar](20) NOT NULL,
 CONSTRAINT [PK_CTPM] PRIMARY KEY 
(
	[MAPM] ASC,
	[MASACH] ASC
)
) ON [PRIMARY]
GO



/****** Object:  ForeignKey [FK_CTPM_PHIEUMUON]    Script Date: 12/03/2021 14:38:17 ******/
ALTER TABLE [dbo].[CTPM]  WITH CHECK ADD  CONSTRAINT [FK_CTPM_PHIEUMUON] FOREIGN KEY([MAPM])
REFERENCES [dbo].[PHIEUMUON] ([MAPM])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

/****** Object:  ForeignKey [FK_CTPM_SACH]    Script Date: 12/03/2021 14:38:17 ******/
ALTER TABLE [dbo].[CTPM]  WITH CHECK ADD  CONSTRAINT [FK_CTPM_SACH] FOREIGN KEY([MASACH])
REFERENCES [dbo].[SACH] ([MASACH])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

/****** Object:  ForeignKey [FK_CTPP_PHIEUPHAT]    Script Date: 12/03/2021 14:38:17 ******/
ALTER TABLE [dbo].[CTPP]  WITH CHECK ADD  CONSTRAINT [FK_CTPP_PHIEUPHAT] FOREIGN KEY([MAPHAT])
REFERENCES [dbo].[PHIEUPHAT] ([MAPHAT])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

/****** Object:  ForeignKey [FK_CTPP_SACH]    Script Date: 12/03/2021 14:38:17 ******/
ALTER TABLE [dbo].[CTPP]  WITH CHECK ADD  CONSTRAINT [FK_CTPP_SACH] FOREIGN KEY([MASACH])
REFERENCES [dbo].[SACH] ([MASACH])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

/****** Object:  ForeignKey [FK_PHIEUMUON_SINHVIEN]    Script Date: 12/03/2021 14:38:17 ******/
ALTER TABLE [dbo].[PHIEUMUON]  WITH CHECK ADD  CONSTRAINT [FK_PHIEUMUON_DOCGIA] FOREIGN KEY([MADG])
REFERENCES [dbo].[DOCGIA] ([MADG])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

/****** Object:  ForeignKey [FK_PHIEUMUON_THUTHU]    Script Date: 12/03/2021 14:38:17 ******/
ALTER TABLE [dbo].[PHIEUMUON]  WITH CHECK ADD  CONSTRAINT [FK_PHIEUMUON_NHANVIEN] FOREIGN KEY([MANV])
REFERENCES [dbo].[NHANVIEN] ([MANV])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

/****** Object:  ForeignKey [FK_PHIEUPHAT_PHIEUPHAT]    Script Date: 12/03/2021 14:38:17 ******/
ALTER TABLE [dbo].[PHIEUPHAT]  WITH CHECK ADD  CONSTRAINT [FK_PHIEUPHAT_PHIEUPHAT] FOREIGN KEY([MAPM])
REFERENCES [dbo].[PHIEUMUON] ([MAPM])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

/****** Object:  ForeignKey [FK_SACH_NXB]    Script Date: 12/03/2021 14:38:17 ******/
ALTER TABLE [dbo].[SACH]  WITH CHECK ADD  CONSTRAINT [FK_SACH_NXB] FOREIGN KEY([MANXB])
REFERENCES [dbo].[NXB] ([MANXB])
ON UPDATE CASCADE
ON DELETE CASCADE
GO


/****** Object:  ForeignKey [FK_SACH_VITRI]    Script Date: 12/03/2021 14:38:17 ******/
ALTER TABLE [dbo].[SACH]  WITH CHECK ADD  CONSTRAINT [FK_SACH_LOAISACH] FOREIGN KEY([MALOAI])
REFERENCES [dbo].[LOAISACH] ([MALOAI])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

/****** Object:  ForeignKey [FK_TAIKHOAN_CHUCVU]    Script Date: 12/03/2021 14:38:17 ******/
ALTER TABLE [dbo].[TAIKHOAN]  WITH CHECK ADD  CONSTRAINT [FK_TAIKHOAN_CHUCVU] FOREIGN KEY([MACV])
REFERENCES [dbo].[CHUCVU] ([MACV])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

/****** Object:  ForeignKey [FK_TAIKHOAN_THUTHU]    Script Date: 12/03/2021 14:38:17 ******/
ALTER TABLE [dbo].[TAIKHOAN]  WITH CHECK ADD  CONSTRAINT [FK_TAIKHOAN_NHANVIEN] FOREIGN KEY([MANV])
REFERENCES [dbo].[NHANVIEN] ([MANV])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

/****** Object:  ForeignKey [FK_LOAISACH_VITRI]    Script Date: 12/03/2021 14:38:17 ******/
ALTER TABLE [dbo].[lOAISACH]  WITH CHECK ADD  CONSTRAINT [FK_LOAISACH_VITRI] FOREIGN KEY([MAVT])
REFERENCES [dbo].[VITRI] ([MAVT])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
