USE [QLTV]
GO
/****** Object:  Table [dbo].[NXB]    Script Date: 10/27/2021 14:53:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[NXB](
	[MANXB] [varchar](10) NOT NULL,
	[TENNXB] [nvarchar](50) NULL,
	[DIACHI] [nvarchar](100) NOT NULL,
	[SDT] [varchar](10) NOT NULL,
	[WEBSIZE] [varchar](100) NOT NULL,
	[EMAIL] [varchar](100) NOT NULL,
 CONSTRAINT [PK_NXB] PRIMARY KEY CLUSTERED 
(
	[MANXB] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[NHANVIEN]    Script Date: 10/27/2021 14:53:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[NHANVIEN](
	[MANV] [varchar](10) NOT NULL,
	[TENNV] [nvarchar](50) NULL,
	[NAMSINH] [date] NOT NULL,
	[DIACHI] [nvarchar](50) NULL,
	[SDT] [varchar](10) NULL,
	[EMAIL] [varchar](50) NULL,
	[NGAYVAOLAM] [date] NOT NULL,
	[gioitinh] [nvarchar](5) NULL,
 CONSTRAINT [PK_NHANVIEN] PRIMARY KEY CLUSTERED 
(
	[MANV] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[LOAISACH]    Script Date: 10/27/2021 14:53:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[LOAISACH](
	[MALOAI] [varchar](10) NOT NULL,
	[TENLOAI] [nvarchar](50) NULL,
 CONSTRAINT [PK_LOAISACH] PRIMARY KEY CLUSTERED 
(
	[MALOAI] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[DOCGIA]    Script Date: 10/27/2021 14:53:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[DOCGIA](
	[MADG] [varchar](10) NOT NULL,
	[HOTEN] [nvarchar](50) NULL,
	[NAMSINH] [date] NULL,
	[DIACHI] [nvarchar](100) NULL,
	[SDT] [varchar](10) NOT NULL,
	[EMAIL] [varchar](50) NULL,
	[GIOITINH] [nchar](10) NULL,
 CONSTRAINT [PK_DOCGIA] PRIMARY KEY CLUSTERED 
(
	[MADG] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[CHUCVU]    Script Date: 10/27/2021 14:53:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[CHUCVU](
	[MACV] [varchar](10) NOT NULL,
	[TENCV] [nvarchar](50) NULL,
 CONSTRAINT [PK_CHUCVU] PRIMARY KEY CLUSTERED 
(
	[MACV] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[PHIEUMUON]    Script Date: 10/27/2021 14:53:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PHIEUMUON](
	[MAPM] [varchar](10) NOT NULL,
	[MANV] [varchar](10) NULL,
	[MADG] [varchar](10) NULL,
	[NGAYMUON] [date] NOT NULL,
	[SOLUONG] [int] NULL,
	[TRANGTHAI] [nvarchar](20) NOT NULL,
 CONSTRAINT [PK_PHIEUMUON] PRIMARY KEY CLUSTERED 
(
	[MAPM] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[VITRI]    Script Date: 10/27/2021 14:53:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[VITRI](
	[MAVT] [varchar](10) NOT NULL,
	[MALOAI] [varchar](10) NULL,
	[TENVITRI] [nvarchar](50) NULL,
 CONSTRAINT [PK_VITRI] PRIMARY KEY CLUSTERED 
(
	[MAVT] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[TAIKHOAN]    Script Date: 10/27/2021 14:53:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TAIKHOAN](
	[MATK] [varchar](10) NOT NULL,
	[TENTK] [varchar](20) NULL,
	[MATKHAU] [varchar](32) NOT NULL,
	[MANV] [varchar](10) NOT NULL,
	[MACV] [varchar](10) NOT NULL,
 CONSTRAINT [PK_TAIKHOAN] PRIMARY KEY CLUSTERED 
(
	[MATK] ASC,
	[MANV] ASC,
	[MACV] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[SACH]    Script Date: 10/27/2021 14:53:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[SACH](
	[MASACH] [varchar](10) NOT NULL,
	[TENSACH] [nvarchar](100) NOT NULL,
	[TACGIA] [nvarchar](100) NOT NULL,
	[SOLUONG] [int] NOT NULL,
	[NAMXB] [numeric](4, 0) NULL,
	[MANXB] [varchar](10) NOT NULL,
	[MAVT] [varchar](10) NULL,
 CONSTRAINT [PK_SACH] PRIMARY KEY CLUSTERED 
(
	[MASACH] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[CTPM]    Script Date: 10/27/2021 14:53:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[CTPM](
	[MAPM] [varchar](10) NOT NULL,
	[MASACH] [varchar](10) NOT NULL,
	[HENTRA] [date] NULL,
	[SOLUONG] [int] NULL,
	[TRANGTHAI] [nvarchar](20) NOT NULL,
 CONSTRAINT [PK_CTPM] PRIMARY KEY CLUSTERED 
(
	[MAPM] ASC,
	[MASACH] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[PHAT]    Script Date: 10/27/2021 14:53:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PHAT](
	[ID_PHAT] [int] IDENTITY(1,1) NOT NULL,
	[LYDOPHAT] [nvarchar](50) NULL,
	[HINHTHUCPHAT] [nvarchar](50) NULL,
	[GhiChu] [nvarchar](50) NULL,
	[NGAYPHAT] [datetime] NULL,
	[TRANGTHAIPHAT] [bit] NULL,
	[MAPM] [varchar](10) NULL,
	[MASACH] [varchar](10) NOT NULL,
 CONSTRAINT [PK_PHAT] PRIMARY KEY CLUSTERED 
(
	[ID_PHAT] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  ForeignKey [FK_CTPM_PHIEUMUON]    Script Date: 10/27/2021 14:53:51 ******/
ALTER TABLE [dbo].[CTPM]  WITH CHECK ADD  CONSTRAINT [FK_CTPM_PHIEUMUON] FOREIGN KEY([MAPM])
REFERENCES [dbo].[PHIEUMUON] ([MAPM])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[CTPM] CHECK CONSTRAINT [FK_CTPM_PHIEUMUON]
GO
/****** Object:  ForeignKey [FK_CTPM_SACH]    Script Date: 10/27/2021 14:53:51 ******/
ALTER TABLE [dbo].[CTPM]  WITH CHECK ADD  CONSTRAINT [FK_CTPM_SACH] FOREIGN KEY([MASACH])
REFERENCES [dbo].[SACH] ([MASACH])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[CTPM] CHECK CONSTRAINT [FK_CTPM_SACH]
GO
/****** Object:  ForeignKey [FK_PHAT_PHIEUMUON]    Script Date: 10/27/2021 14:53:51 ******/
ALTER TABLE [dbo].[PHAT]  WITH CHECK ADD  CONSTRAINT [FK_PHAT_PHIEUMUON] FOREIGN KEY([MAPM], [MASACH])
REFERENCES [dbo].[CTPM] ([MAPM], [MASACH])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[PHAT] CHECK CONSTRAINT [FK_PHAT_PHIEUMUON]
GO
/****** Object:  ForeignKey [FK_PHIEUMUON_SINHVIEN]    Script Date: 10/27/2021 14:53:51 ******/
ALTER TABLE [dbo].[PHIEUMUON]  WITH CHECK ADD  CONSTRAINT [FK_PHIEUMUON_SINHVIEN] FOREIGN KEY([MADG])
REFERENCES [dbo].[DOCGIA] ([MADG])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[PHIEUMUON] CHECK CONSTRAINT [FK_PHIEUMUON_SINHVIEN]
GO
/****** Object:  ForeignKey [FK_PHIEUMUON_THUTHU]    Script Date: 10/27/2021 14:53:51 ******/
ALTER TABLE [dbo].[PHIEUMUON]  WITH CHECK ADD  CONSTRAINT [FK_PHIEUMUON_THUTHU] FOREIGN KEY([MANV])
REFERENCES [dbo].[NHANVIEN] ([MANV])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[PHIEUMUON] CHECK CONSTRAINT [FK_PHIEUMUON_THUTHU]
GO
/****** Object:  ForeignKey [FK_SACH_NXB]    Script Date: 10/27/2021 14:53:51 ******/
ALTER TABLE [dbo].[SACH]  WITH CHECK ADD  CONSTRAINT [FK_SACH_NXB] FOREIGN KEY([MANXB])
REFERENCES [dbo].[NXB] ([MANXB])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[SACH] CHECK CONSTRAINT [FK_SACH_NXB]
GO
/****** Object:  ForeignKey [FK_SACH_VITRI]    Script Date: 10/27/2021 14:53:51 ******/
ALTER TABLE [dbo].[SACH]  WITH CHECK ADD  CONSTRAINT [FK_SACH_VITRI] FOREIGN KEY([MAVT])
REFERENCES [dbo].[VITRI] ([MAVT])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[SACH] CHECK CONSTRAINT [FK_SACH_VITRI]
GO
/****** Object:  ForeignKey [FK_TAIKHOAN_CHUCVU]    Script Date: 10/27/2021 14:53:51 ******/
ALTER TABLE [dbo].[TAIKHOAN]  WITH CHECK ADD  CONSTRAINT [FK_TAIKHOAN_CHUCVU] FOREIGN KEY([MACV])
REFERENCES [dbo].[CHUCVU] ([MACV])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[TAIKHOAN] CHECK CONSTRAINT [FK_TAIKHOAN_CHUCVU]
GO
/****** Object:  ForeignKey [FK_TAIKHOAN_THUTHU]    Script Date: 10/27/2021 14:53:51 ******/
ALTER TABLE [dbo].[TAIKHOAN]  WITH CHECK ADD  CONSTRAINT [FK_TAIKHOAN_THUTHU] FOREIGN KEY([MANV])
REFERENCES [dbo].[NHANVIEN] ([MANV])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[TAIKHOAN] CHECK CONSTRAINT [FK_TAIKHOAN_THUTHU]
GO
/****** Object:  ForeignKey [FK_VITR_LOAISACH]    Script Date: 10/27/2021 14:53:51 ******/
ALTER TABLE [dbo].[VITRI]  WITH CHECK ADD  CONSTRAINT [FK_VITR_LOAISACH] FOREIGN KEY([MALOAI])
REFERENCES [dbo].[LOAISACH] ([MALOAI])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[VITRI] CHECK CONSTRAINT [FK_VITR_LOAISACH]
GO
