CREATE TABLE [dbo].[LOAISACH] (
    [MALOAI]  VARCHAR (10)  NOT NULL,
    [TENLOAI] NVARCHAR (50) NULL,
    [MAVT]    VARCHAR (10)  NULL,
    CONSTRAINT [PK_LOAISACH] PRIMARY KEY CLUSTERED ([MALOAI] ASC),
    CONSTRAINT [FK_LOAISACH_VITRI] FOREIGN KEY ([MAVT]) REFERENCES [dbo].[VITRI] ([MAVT]) ON DELETE CASCADE ON UPDATE CASCADE
);

