CREATE TABLE [dbo].[NHANVIEN] (
    [MANV]       VARCHAR (10)   NOT NULL,
    [TENNV]      NVARCHAR (50)  NULL,
    [NAMSINH]    DATE           NULL,
    [DIACHI]     NVARCHAR (100) NULL,
    [SDT]        VARCHAR (10)   NULL,
    [EMAIL]      VARCHAR (50)   NULL,
    [NGAYVAOLAM] DATE           NOT NULL,
    [GIOITINH]   NVARCHAR (10)  NOT NULL,
    CONSTRAINT [PK_NHANVIEN] PRIMARY KEY CLUSTERED ([MANV] ASC)
);

