CREATE TABLE [dbo].[NXB] (
    [MANXB]   VARCHAR (10)   NOT NULL,
    [TENNXB]  NVARCHAR (50)  NULL,
    [DIACHI]  NVARCHAR (100) NOT NULL,
    [SDT]     VARCHAR (10)   NOT NULL,
    [WEBSIZE] VARCHAR (100)  NOT NULL,
    [EMAIL]   VARCHAR (100)  NOT NULL,
    CONSTRAINT [PK_NXB] PRIMARY KEY CLUSTERED ([MANXB] ASC)
);

