CREATE TABLE [dbo].[PHIEUMUON] (
    [MAPM]      VARCHAR (10)  NOT NULL,
    [MANV]      VARCHAR (10)  NULL,
    [MADG]      VARCHAR (10)  NULL,
    [NGAYMUON]  DATE          NOT NULL,
    [SOLUONG]   INT           NULL,
    [TRANGTHAI] NVARCHAR (20) NOT NULL,
    CONSTRAINT [PK_PHIEUMUON] PRIMARY KEY CLUSTERED ([MAPM] ASC),
    CONSTRAINT [FK_PHIEUMUON_DOCGIA] FOREIGN KEY ([MADG]) REFERENCES [dbo].[DOCGIA] ([MADG]) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT [FK_PHIEUMUON_NHANVIEN] FOREIGN KEY ([MANV]) REFERENCES [dbo].[NHANVIEN] ([MANV]) ON DELETE CASCADE ON UPDATE CASCADE
);

